# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sA-MLugptXpmeNaUDCax5-lbNwtfNwkM
"""

import streamlit as st
import pandas as pd
import joblib
import io
import matplotlib.pyplot as plt
import pickle

# ------------------------------
# PAGE CONFIGURATION
# ------------------------------
st.set_page_config(
    page_title="Disease Prediction Portal",
    # page_icon="🩺",
    layout="centered"
)

# ------------------------------
# LOAD MODELS (cached)
# ------------------------------
@st.cache_resource
def load_models():
    """Load all trained ML models once"""
    kidney_model = joblib.load('models/kidney.joblib')
    heart_model = joblib.load('models/heart.joblib')
    diabetes_model = joblib.load('models/diabetes.joblib')
    return kidney_model, heart_model, diabetes_model

kidney_model, heart_model, diabetes_model = load_models()

# ------------------------------
# HELPER FUNCTION
# ------------------------------
def read_txt_to_dataframe(uploaded_file):
    """
    Reads a TXT file into a pandas DataFrame.
    Assumes data is space or comma separated.
    """
    try:
        # Try comma-separated first
        data = pd.read_csv(uploaded_file)
    except Exception:
        # Try space/tab separated
        uploaded_file.seek(0)
        data = pd.read_csv(uploaded_file, delim_whitespace=True)
    return data


# ------------------------------
# APP UI
# ------------------------------
st.title("Disease Prediction Portal")
st.markdown("""
Upload a **.txt** file containing the patient's health data.
You can choose to analyze for **Kidney Disease**, **Heart Disease**, or **Diabetes**.
""")

uploaded_file = st.file_uploader("Upload patient data (.txt file)", type=["txt"])

model_choice = st.selectbox(
    "Select model to run:",
    ["Kidney Disease", "Heart Disease", "Diabetes"]
)

# ------------------------------
# PROCESSING LOGIC
# ------------------------------
if uploaded_file is not None:
    try:
        df = read_txt_to_dataframe(uploaded_file)
        st.subheader("Uploaded Patient Data")
        st.dataframe(df.head())

        if st.button("Analyze Data"):
            st.info("Running models... Please wait.")
            results = {}

            # Run selected models
            if model_choice in ["Kidney Disease"]:
                pred = kidney_model.predict(df)[0]
                prob = kidney_model.predict_proba(df)[0].max() if hasattr(kidney_model, "predict_proba") else None
                results['Kidney Disease'] = (pred, prob)

            if model_choice in ["Heart Disease"]:
                pred = heart_model.predict(df)[0]
                prob = heart_model.predict_proba(df)[0][1] if hasattr(heart_model, "predict_proba") else None
                print(prob)
                results['Heart Disease'] = (pred, prob)

            if model_choice in ["Diabetes"]:
                pred = diabetes_model.predict(df)[0]
                prob = diabetes_model.predict_proba(df)[0].max() if hasattr(diabetes_model, "predict_proba") else None
                results['Diabetes'] = (pred, prob)

            # Display results
            st.success("Analysis Complete!")
            st.subheader("Prediction Results")

            display_df = pd.DataFrame([
                {"Disease": k, "Prediction": v[0], "Probability": f"{v[1]*100:.2f}%" if v[1] else "N/A"}
                for k, v in results.items()
            ])

            st.table(display_df)

            st.subheader("Summary Report")
            for disease, (prediction, probability) in results.items():
                if probability is not None:
                    # Format for one decimal place, like your 13.0% example
                    prob_percent = f"{probability * 100:.1f}%"

                    font_size = "20px"  # Try changing this to '24px' or '1.5em'

                    if prob_percent:  # Assuming prob_percent is defined and not None/0
                        # Use HTML <strong> for bold text
                        styled_text = f"• Based on the report, there is a <strong>{prob_percent}</strong> probability of the patient having <strong>{disease}</strong>."

                        st.markdown(
                            f'<p style="font-size: {font_size};">{styled_text}</p>',
                            unsafe_allow_html=True
                        )
                    else:
                        styled_text = f"• Analysis for <strong>{disease}</strong> did not return a probability."

                        # You can style the "else" case too
                        st.markdown(
                            f'<p style="font-size: {font_size}; color: #888888;">{styled_text}</p>',
                            unsafe_allow_html=True
                        )
            # Visualization
            st.subheader("Probability Visualization")
            prob_data = [v[1] for v in results.values() if v[1] is not None]
            labels = [k for k, v in results.items() if v[1] is not None]

            if prob_data:
                fig, ax = plt.subplots(figsize=(6, 4))
                ax.bar(labels, prob_data, color='skyblue')
                ax.set_ylabel("Probability")
                ax.set_ylim(0, 1)
                ax.set_title("Model Confidence Levels")
                st.pyplot(fig)
            else:
                st.info("No probability data available for visualization.")

    except Exception as e:
        st.error(f"Error reading file: {e}")

else:
    st.info("Please upload a .txt file to begin.")
