# -*- coding: utf-8 -*-
"""Heart Disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZFmX8FhcHNKo9CpHpJlzhBg2Qj8op20
"""

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
import pickle
from joblib import dump

"""## UCI Heart Disease Dataset"""

# fetch dataset
heart_disease_uci = fetch_ucirepo(id=45)

# data (as pandas dataframes)
X = heart_disease_uci.data.features
y = heart_disease_uci.data.targets

# metadata
print(heart_disease_uci.metadata)

# variable information
print(heart_disease_uci.variables)

# Combine features + target into one dataframe for convenience
df_uci = pd.concat([X, y], axis=1)

print("===== Dataset Overview =====")
print(f"Shape: {df_uci.shape}")
print("Columns:", df_uci.columns.tolist())
print("\nMissing values per column:\n", df_uci.isnull().sum())
print("\nData types:\n", df_uci.dtypes)

print("\n===== Statistical Summary =====")
print(df_uci.describe(include="all"))

# Unique values for categorical-like columns
print("\n===== Unique Values (for categorical columns) =====")
for col in df_uci.columns:
    if df_uci[col].nunique() < 20:
        print(f"{col}: {sorted(df_uci[col].dropna().unique())}")

# Target distribution (num = 0–4, but often binarized)
target_col = y.columns[0]
print("\n===== Target Distribution (Original multi-class) =====")
print(df_uci[target_col].value_counts())

# Binarize: 0 = no disease, 1 = disease present
df_uci['target_bin'] = df_uci[target_col].apply(lambda x: 1 if x > 0 else 0)
print("\n===== Target Distribution (Binarized) =====")
print(df_uci['target_bin'].value_counts(normalize=True))

# Some additional highlights
if "age" in df_uci.columns:
    print("\nAge stats:")
    print(f"Min: {df_uci['age'].min()}, Max: {df_uci['age'].max()}, Mean: {df_uci['age'].mean():.2f}")

if "trestbps" in df_uci.columns:
    print(f"\nResting BP (trestbps) - Mean: {df_uci['trestbps'].mean():.1f}, "
          f"Range: {df_uci['trestbps'].min()}–{df_uci['trestbps'].max()}")

if "chol" in df_uci.columns:
    print(f"\nCholesterol (chol) - Mean: {df_uci['chol'].mean():.1f}, "
          f"Range: {df_uci['chol'].min()}–{df_uci['chol'].max()}")

if "thalach" in df_uci.columns:
    print(f"\nMax Heart Rate (thalach) - Mean: {df_uci['thalach'].mean():.1f}, "
          f"Range: {df_uci['thalach'].min()}–{df_uci['thalach'].max()}")

if "oldpeak" in df_uci.columns:
    print(f"\nST Depression (oldpeak) - Mean: {df_uci['oldpeak'].mean():.2f}, "
          f"Range: {df_uci['oldpeak'].min()}–{df_uci['oldpeak'].max()}")

print("\n===== Analysis Complete =====")

df_uci

"""## IEEE Heart Disease Dataset"""

# Load IEEE Heart Disease dataset
file_path = "heart_statlog_cleveland_hungary_final.csv"  # change path if needed
df_ieee = pd.read_csv(file_path)

print("===== Dataset Overview =====")
print(f"Shape: {df_ieee.shape}")
print("Columns:", df_ieee.columns.tolist())
print("\nMissing values per column:\n", df_ieee.isnull().sum())
print("\nData types:\n", df_ieee.dtypes)

print("\n===== Statistical Summary =====")
print(df_ieee.describe(include="all"))

print("\n===== Unique Values (categorical-like columns) =====")
for col in df_ieee.columns:
    if df_ieee[col].nunique() < 20:
        print(f"{col}: {df_ieee[col].unique()}")

print("\n===== Target Distribution =====")
if "target" in df_ieee.columns:
    print(df_ieee["target"].value_counts())

# Extract highlights for key medical features
highlights = {}

if "age" in df_ieee.columns:
    highlights["age"] = {
        "min": df_ieee["age"].min(),
        "max": df_ieee["age"].max(),
        "mean": round(df_ieee["age"].mean(), 2)
    }

if "resting bp s" in df_ieee.columns:
    highlights["resting bp s"] = {
        "min": df_ieee["resting bp s"].min(),
        "max": df_ieee["resting bp s"].max(),
        "mean": round(df_ieee["resting bp s"].mean(), 2)
    }

if "cholesterol" in df_ieee.columns:
    highlights["cholesterol"] = {
        "min": df_ieee["cholesterol"].min(),
        "max": df_ieee["cholesterol"].max(),
        "mean": round(df_ieee["cholesterol"].mean(), 2)
    }

if "max heart rate" in df_ieee.columns:
    highlights["max heart rate"] = {
        "min": df_ieee["max heart rate"].min(),
        "max": df_ieee["max heart rate"].max(),
        "mean": round(df_ieee["max heart rate"].mean(), 2)
    }

if "oldpeak" in df_ieee.columns:
    highlights["oldpeak"] = {
        "min": df_ieee["oldpeak"].min(),
        "max": df_ieee["oldpeak"].max(),
        "mean": round(df_ieee["oldpeak"].mean(), 2)
    }

print("\n===== Key Feature Highlights =====")
for k, v in highlights.items():
    print(f"{k}: {v}")

print("\n===== Analysis Complete =====")

"""## Rename the columns for IEEE Heart Disease Dataset"""

df_ieee.rename(columns={'chest pain type': 'cp', 'resting bp s':'trestbps', 'cholesterol': 'chol', 'fasting blood sugar': 'fbs', 'max heart rate': 'thalach', 'resting ecg': 'restecg', 'exercise angina': 'exang', 'ST slope': 'slope', 'target': 'target_bin'}, inplace=True)

df_ieee

"""## Kaggle Heart Failure Prediction Dataset"""

# Load Heart Disease dataset
file_path = "Kaggle_Heart_Failure_Dataset.xls"  # change path if needed
df_1 = pd.read_csv(file_path)

print("===== Dataset Overview =====")
print(f"Shape: {df_1.shape}")
print("Columns:", df_1.columns.tolist())
print("\nMissing values per column:\n", df_1.isnull().sum())
print("\nData types:\n", df_1.dtypes)

pd.set_option('future.no_silent_downcasting', True)

df_1['Sex'] = df_1['Sex'].replace({'M': 1, 'F': 0})
df_1['Sex'] = pd.to_numeric(df_1['Sex'], errors='raise')

df_1['ChestPainType'] = df_1['ChestPainType'].replace({'NAP': 3, 'TA': 1, 'ATA': 2, 'ASY': 4})
df_1['ChestPainType'] = pd.to_numeric(df_1['ChestPainType'], errors='raise')

df_1['RestingECG'] = df_1['RestingECG'].replace({'Normal': 0, 'ST': 1, 'LVH': 2})
df_1['RestingECG'] = pd.to_numeric(df_1['RestingECG'], errors='raise')

df_1['ExerciseAngina'] = df_1['ExerciseAngina'].replace({'N': 0, 'Y': 1})
df_1['ExerciseAngina'] = pd.to_numeric(df_1['ExerciseAngina'], errors='raise')

df_1['ST_Slope'] = df_1['ST_Slope'].replace({'Flat': 0, 'Up': 1, 'Down': 2})
df_1['ST_Slope'] = pd.to_numeric(df_1['ST_Slope'], errors='raise')

df_1.infer_objects(copy=False)
df_1.dtypes

print("\n===== Statistical Summary =====")
print(df_1.describe(include="all"))

print("\n===== Unique Values (categorical-like columns) =====")
for col in df_1.columns:
    if df_1[col].nunique() < 20:
        print(f"{col}: {df_1[col].unique()}")

print("\n===== Target Distribution =====")
if "HeartDisease" in df_1.columns:
    print(df_1["HeartDisease"].value_counts())

# Extract highlights for key medical features
highlights = {}

if "Age" in df_1.columns:
    highlights["Age"] = {
        "min": df_1["Age"].min(),
        "max": df_1["Age"].max(),
        "mean": round(df_1["Age"].mean(), 2)
    }

if "RestingBP" in df_1.columns:
    highlights["RestingBP"] = {
        "min": df_1["RestingBP"].min(),
        "max": df_1["RestingBP"].max(),
        "mean": round(df_1["RestingBP"].mean(), 2)
    }

if "Cholesterol" in df_1.columns:
    highlights["Cholesterol"] = {
        "min": df_1["Cholesterol"].min(),
        "max": df_1["Cholesterol"].max(),
        "mean": round(df_1["Cholesterol"].mean(), 2)
    }

if "MaxHR" in df_1.columns:
    highlights["MaxHR"] = {
        "min": df_1["MaxHR"].min(),
        "max": df_1["MaxHR"].max(),
        "mean": round(df_1["MaxHR"].mean(), 2)
    }

if "Oldpeak" in df_1.columns:
    highlights["Oldpeak"] = {
        "min": df_1["Oldpeak"].min(),
        "max": df_1["Oldpeak"].max(),
        "mean": round(df_1["Oldpeak"].mean(), 2)
    }

print("\n===== Key Feature Highlights =====")
for k, v in highlights.items():
    print(f"{k}: {v}")

print("\n===== Analysis Complete =====")

df_1.rename(columns={'Age': 'age', 'Sex': 'sex', 'ChestPainType': 'cp', 'RestingBP':'trestbps', 'Cholesterol': 'chol', 'FastingBS': 'fbs', 'MaxHR': 'thalach', 'RestingECG': 'restecg', 'ExerciseAngina': 'exang', 'ST_Slope': 'slope', 'HeartDisease': 'target_bin', 'Oldpeak': 'oldpeak'}, inplace=True)

df_1

"""## Heart Disease Dataset 4"""

# Load Heart Disease dataset
file_path = "heart.xls"  # change path if needed
df_2 = pd.read_csv(file_path)

print("===== Dataset Overview =====")
print(f"Shape: {df_2.shape}")
print("Columns:", df_2.columns.tolist())
print("\nMissing values per column:\n", df_2.isnull().sum())
print("\nData types:\n", df_2.dtypes)

print("\n===== Statistical Summary =====")
print(df_2.describe(include="all"))

# Unique values for categorical-like columns
print("\n===== Unique Values (for categorical columns) =====")
for col in df_2.columns:
    if df_2[col].nunique() < 20:
        print(f"{col}: {sorted(df_2[col].dropna().unique())}")

# Target distribution (num = 0–4, but often binarized)
print("\n===== Target Distribution (Original multi-class) =====")
print(df_2['target'].value_counts())

# Binarize: 0 = no disease, 1 = disease present
# df_2['target_bin'] = df_2[target_col].apply(lambda x: 1 if x > 0 else 0)
# print("\n===== Target Distribution (Binarized) =====")
# print(df_2['target_bin'].value_counts(normalize=True))

# Some additional highlights
if "age" in df_2.columns:
    print("\nAge stats:")
    print(f"Min: {df_2['age'].min()}, Max: {df_2['age'].max()}, Mean: {df_2['age'].mean():.2f}")

if "trestbps" in df_2.columns:
    print(f"\nResting BP (trestbps) - Mean: {df_2['trestbps'].mean():.1f}, "
          f"Range: {df_2['trestbps'].min()}–{df_2['trestbps'].max()}")

if "chol" in df_2.columns:
    print(f"\nCholesterol (chol) - Mean: {df_2['chol'].mean():.1f}, "
          f"Range: {df_2['chol'].min()}–{df_2['chol'].max()}")

if "thalach" in df_2.columns:
    print(f"\nMax Heart Rate (thalach) - Mean: {df_2['thalach'].mean():.1f}, "
          f"Range: {df_2['thalach'].min()}–{df_2['thalach'].max()}")

if "oldpeak" in df_2.columns:
    print(f"\nST Depression (oldpeak) - Mean: {df_2['oldpeak'].mean():.2f}, "
          f"Range: {df_2['oldpeak'].min()}–{df_2['oldpeak'].max()}")

print("\n===== Analysis Complete =====")

"""## Rename Heart Disease Dataset 4 Columns  """

df_2.rename(columns={'target': 'target_bin'}, inplace=True)

"""## Cardiovascular Disease Dataset"""

# Load Heart Disease dataset
file_path = "Cardiovascular_Disease_Dataset.csv"  # change path if needed
df_cdd = pd.read_csv(file_path)

print("===== Dataset Overview =====")
print(f"Shape: {df_cdd.shape}")
print("Columns:", df_cdd.columns.tolist())
print("\nMissing values per column:\n", df_cdd.isnull().sum())
print("\nData types:\n", df_cdd.dtypes)

print("\n===== Statistical Summary =====")
print(df_cdd.describe(include="all"))

# Unique values for categorical-like columns
print("\n===== Unique Values (for categorical columns) =====")
for col in df_cdd.columns:
    if df_cdd[col].nunique() < 20:
        print(f"{col}: {sorted(df_cdd[col].dropna().unique())}")

# Target distribution (num = 0–4, but often binarized)
print("\n===== Target Distribution (Original multi-class) =====")
print(df_cdd['target'].value_counts())

# Binarize: 0 = no disease, 1 = disease present
# df_cdd['target_bin'] = df_cdd[target_col].apply(lambda x: 1 if x > 0 else 0)
# print("\n===== Target Distribution (Binarized) =====")
# print(df_cdd['target_bin'].value_counts(normalize=True))

# Some additional highlights
if "age" in df_cdd.columns:
    print("\nAge stats:")
    print(f"Min: {df_cdd['age'].min()}, Max: {df_cdd['age'].max()}, Mean: {df_cdd['age'].mean():.2f}")

if "restingBP" in df_cdd.columns:
    print(f"\nResting BP (restingBP) - Mean: {df_cdd['restingBP'].mean():.1f}, "
          f"Range: {df_cdd['restingBP'].min()}–{df_cdd['restingBP'].max()}")

if "serumcholestrol" in df_cdd.columns:
    print(f"\nCholesterol (serumcholestrol) - Mean: {df_cdd['serumcholestrol'].mean():.1f}, "
          f"Range: {df_cdd['serumcholestrol'].min()}–{df_cdd['serumcholestrol'].max()}")

if "maxheartrate" in df_cdd.columns:
    print(f"\nMax Heart Rate (maxheartrate) - Mean: {df_cdd['maxheartrate'].mean():.1f}, "
          f"Range: {df_cdd['maxheartrate'].min()}–{df_cdd['maxheartrate'].max()}")

if "oldpeak" in df_cdd.columns:
    print(f"\nST Depression (oldpeak) - Mean: {df_cdd['oldpeak'].mean():.2f}, "
          f"Range: {df_cdd['oldpeak'].min()}–{df_cdd['oldpeak'].max()}")

print("\n===== Analysis Complete =====")

df_cdd.rename(columns={'target': 'target_bin', 'gender': 'sex', 'chestpain': 'cp', 'restingBP': 'trestbps', 'serumcholestrol': 'chol', 'fastingbloodsugar': 'fbs', 'restingrelectro': 'restecg', 'maxheartrate': 'thalach', 'exerciseangia': 'exang'}, inplace=True)

df_cdd

"""## Combine two dataframes"""

combined_df = pd.concat([df_uci, df_ieee, df_1, df_2, df_cdd], ignore_index=True)
combined_df.drop(columns=['num'], inplace=True)
combined_df.drop(columns=['ca', 'thal'], inplace=True)
combined_df.drop(columns=['patientid', 'noofmajorvessels'], inplace=True)

print("===== Combined Dataset Overview =====")
print(f"Shape: {combined_df.shape}")
print("Columns:", combined_df.columns.tolist())

"""## Clean Data"""

combined_df.drop_duplicates(inplace=True)

combined_df

X = combined_df.loc[ : , combined_df.columns != 'target_bin']
Y = combined_df['target_bin']

Y.value_counts()

combined_df.to_csv('final_data.csv', index=False)

final_combined_df = pd.read_csv('augmented_final_data.csv')
X = final_combined_df.loc[ : , final_combined_df.columns != 'target_bin']
Y = final_combined_df['target_bin']

final_combined_df.shape

Y.value_counts()

"""## Model Configuration"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from imblearn.over_sampling import SMOTE

# Models

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

import sklearn
print(sklearn.__version__)

# train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42, stratify=Y)

y_test = y_test.values.ravel()
y_train = y_train.values.ravel()

# Scale your features
# For models like Logistic Regression, KNN, SVM

# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# Fix Class Imbalance

# sm = SMOTE()
# X_train, y_train = sm.fit_resample(X_train, y_train)

# Define the models
from xgboost import XGBClassifier

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    # "Random Forest": RandomForestClassifier({'max_depth': 12, 'min_samples_split': 2, 'n_estimators': 200}),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC(),
    "XGBC": XGBClassifier(eval_metric='logloss')
}

# train and evaluate

results = {}

# Identify numerical and categorical features
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])


preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])


for name, model in models.items():
  clf = Pipeline(steps=[("preprocessor", preprocessor), ("classifier", model)])
  clf.fit(X_train, y_train)
  if name == "Random Forest":
    dump(clf, 'heart.joblib')
  y_pred = clf.predict(X_test)
  acc = accuracy_score(y_test, y_pred)
  results[name] = acc

  print(f"\n{name}")
  print(f"Accuracy: {acc}")
  print(classification_report(y_test, y_pred))
  print(confusion_matrix(y_test, y_pred))
  print("\n")

# Example single input (make sure order & feature names match your dataset)
single_input = {
    'age': 63,
    'sex': 1,
    'cp': 1,
    'trestbps': 145,
    'chol': 233,
    'fbs': 1,
    'restecg': 2,
    'thalach': 150,
    'exang': 0,
    'oldpeak': 2.3,
    'slope': 3,
    'target_bin': 0
}

# Convert single input to dataframe so pipeline accepts it
import pandas as pd

single_df = pd.DataFrame([single_input])  # wrap in a list to make a single row DataFrame

# Use one of the trained models, e.g. Logistic Regression
selected_model = results_model = RandomForestClassifier()

# Build pipeline again for prediction
clf = Pipeline(steps=[("preprocessor", preprocessor), ("classifier", selected_model)])
clf.fit(X_train, y_train)

# Predict class
prediction = clf.predict(single_df)[0]

prob = clf.predict_proba(single_df)[0][1] if hasattr(clf, "predict_proba") else None

# Predict probabilities
probabilities = clf.predict_proba(single_df)[0]  # returns array like [0.32, 0.68]
print(probabilities)

print(f"Based on the symptons, there is {round(probabilities[1] * 100, 2)}% probability of the patient having Heart Disease.")

print(prediction, prob)
# Print nicely
# print(f"Predicted Class: {prediction}")
# for cls, prob in zip(clf.classes_, probabilities):
#     print(f"Probability of {cls}: {round(prob * 100, 2)}%")

# from sklearn.model_selection import GridSearchCV
# from sklearn.ensemble import RandomForestClassifier

# params = {
#     'n_estimators':[100,200,500,1000],
#     'max_depth':[3,5,7,12],
#     'min_samples_split':[2,5,10]
# }

# grid = GridSearchCV(RandomForestClassifier(), params, cv=5, scoring='roc_auc')
# grid.fit(X_train, y_train)
# {'max_depth': 12, 'min_samples_split': 2, 'n_estimators': 200}
# print(grid.best_params_)
# print(grid.best_score_)

# best_model = grid.best_estimator_
# y_pred_proba = best_model.predict_proba(X_test)[:,1]



# Age: Higher age is strongly associated with increased risks.​ - P

# Gender: Predictive differences have been established between males and females.​ - P

# Blood Pressure: Systolic and diastolic blood pressure are major contributors.​

# Cholesterol Level: Both total cholesterol and subtypes (HDL, LDL, triglycerides) are predictive.​ - P

# Smoking Status: History of smoking significantly raises risk.​

# Family History: A family background of heart disease increases susceptibility.​

# Obesity/BMI: Obesity or high body mass index is a known risk factor.​

# Diabetes: Presence of diabetes markedly elevates risk.​

# Physical Inactivity: Sedentary lifestyle is an independent risk factor.​

# Chest Pain Type: Diagnostic chest pain categories help stratify risk.​ - P

# Resting Electrocardiogram (ECG) Results: Abnormal ECG readings are strongly linked to disease.​ - P

# Platelet Count: Recently identified as an influential laboratory marker.​

# LDL/HDL Ratios: Lipid profile details further inform risk.​

# Stress Levels: Recent studies highlight the role of chronic stress.​

# Prior Treatment History: Includes interventions and prior cardiovascular symptoms.​

# Diet: Poor dietary habits enhance risk.​

# Alcohol Consumption: Often considered in multiclass models.​

# Estimated Glomerular Filtration Rate (eGFR): Renal function impacts cardiovascular health.​

# Carotid Artery Thickness (IMT): Emerging as an important clinical measure.

# https://pmc.ncbi.nlm.nih.gov/articles/PMC10258084/
# https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0284103
# https://pmc.ncbi.nlm.nih.gov/articles/PMC10036320/

y_pred_proba = selected_model.predict_proba(X_test)[:, 1]

from sklearn.metrics import roc_auc_score
print("AUC:", roc_auc_score(y_test, y_pred_proba))

#Cross Validation Scores

from sklearn.model_selection import cross_val_score
scores = cross_val_score(RandomForestClassifier(), X, Y, cv=10, scoring='accuracy')
print(scores.mean())

"""1. Family history	Nominal	Yes, No
2. Smoking	Nominal	Yes, No
3. Obesity	Nominal	Yes, No
4. Troponin	Nominal	Positive, Negative
"""

