# -*- coding: utf-8 -*-
"""ckd_aug_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QYiT4SGB0qAuo22yBxqndYM_GsxTjgGr
"""

from google.colab import files
uploaded = files.upload()  # Upload: CKD_Augmented.csv

import pandas as pd

df = pd.read_csv("CKD_Augmented.csv")
print(df.head())
print(df.info())

top15 = [
    "DiastolicBP", "Age", "SystolicBP", "ACR", "SerumCreatinine",
    "GFR", "BUNLevels", "HemoglobinLevels", "FastingBloodSugar",
    "CholesterolTotal", "CholesterolLDL", "HbA1c",
    "CholesterolHDL", "CholesterolTriglycerides",
    "SerumElectrolytesCalcium"
]

target = "class"   # change this if your dataset uses a different label

df = df[top15 + [target]]
df.head()

df = df.replace(["?", "NA", "nan", "NaN"], pd.NA)

for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors="ignore")

df = df.dropna(subset=["class"])
df = df.fillna(df.median(numeric_only=True))

df.head()

from sklearn.model_selection import train_test_split

X = df[top15]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=250,
    max_depth=None,
    class_weight="balanced",
    random_state=42
)

model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, zero_division=0))
print("Recall:", recall_score(y_test, y_pred, zero_division=0))
print("F1 Score:", f1_score(y_test, y_pred, zero_division=0))

import matplotlib.pyplot as plt

plt.figure(figsize=(7,10))
plt.barh(top15, model.feature_importances_)
plt.title("Feature Importance (Top 15)")
plt.show()

dummy = pd.DataFrame([{
    "DiastolicBP": 82,
    "Age": 55,
    "SystolicBP": 138,
    "ACR": 45,
    "SerumCreatinine": 1.3,
    "GFR": 72,
    "BUNLevels": 22,
    "HemoglobinLevels": 13.2,
    "FastingBloodSugar": 98,
    "CholesterolTotal": 185,
    "CholesterolLDL": 112,
    "HbA1c": 5.8,
    "CholesterolHDL": 48,
    "CholesterolTriglycerides": 132,
    "SerumElectrolytesCalcium": 9.1
}])

print("Prediction:", model.predict(dummy)[0])
print("Probability:", model.predict_proba(dummy))

import joblib

# Save the trained model
joblib.dump(model, "ckd_model_pred.joblib")

print("Model saved as ckd_model.joblib")

X = df.drop("class", axis=1)   # features
y = df["class"]                # target

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42
)

model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, zero_division=0))
print("Recall:", recall_score(y_test, y_pred, zero_division=0))
print("F1 Score:", f1_score(y_test, y_pred, zero_division=0))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

import matplotlib.pyplot as plt

importances = model.feature_importances_
feature_names = X.columns

plt.figure(figsize=(8, 10))
plt.barh(feature_names, importances)
plt.title("Feature Importance")
plt.show()

import joblib
joblib.dump(model, "ckd_model.joblib")
print("Model saved as ckd_model.joblib")

patient_data = {
    "DiastolicBP": 82,
    "Age": 55,
    "SystolicBP": 138,
    "ACR": 45,
    "SerumCreatinine": 1.3,
    "GFR": 72,
    "BUNLevels": 22,
    "HemoglobinLevels": 13.2,
    "FastingBloodSugar": 98,
    "CholesterolTotal": 185,
    "CholesterolLDL": 112,
    "HbA1c": 5.8,
    "CholesterolHDL": 48,
    "CholesterolTriglycerides": 132,
    "SerumElectrolytesCalcium": 9.1
}

# Create a DataFrame from the patient data and reindex to include all X columns
dummy = pd.DataFrame([patient_data]).reindex(columns=X.columns, fill_value=pd.NA)

# Fill any remaining NA values (for columns not provided) with the median from the training data
dummy = dummy.fillna(X_train.median(numeric_only=True))

print("Prediction:", model.predict(dummy))
print("Probability:", model.predict_proba(dummy))

