# -*- coding: utf-8 -*-
"""Diabetes_Extracted_Column.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MsdZSgtcyFWkI3T5qOBMuZfRQRoJ-vH5
"""

pip install pandas pyreadstat requests tqdm

from google.colab import files
uploaded = files.upload()

import pandas as pd
import pyreadstat

# Load base diabetes CSV
df_diabetes = pd.read_csv("NHANES_diabetes.csv")

url = "https://wwwn.cdc.gov/Nchs/Nhanes/2017-2020/BIOPRO_J.XPT"

print("Downloading NHANES lab data from:", url)
df_lab, meta = pyreadstat.read_xport(url)
print("Lab file loaded with", len(df_lab), "rows and", len(df_lab.columns), "columns.")

# Select only the needed columns
lab_vars = ["SEQN", "URXUAC", "LBXTR", "LBXTC"]
df_lab = df_lab[lab_vars]

# Merge with data
df_merged = df_diabetes.merge(df_lab, on="SEQN", how="left")

# Save merged file
df_merged.to_csv("NHANES_diabetes_with_labs.csv", index=False)
print("Done! File saved as NHANES_diabetes_with_labs.csv")

