# -*- coding: utf-8 -*-
"""ETL_Diabetes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOVLuOlUfmG5EKyFUvHrZ2dPrUSnS4up
"""

!pip install --upgrade --no-deps --force-reinstall pyreadstat xport

!fusermount -u /content/drive 2>/dev/null || true
!rm -rf /content/drive  # remove old mount folder if stuck

!mkdir /content/drive

from google.colab import drive
drive.mount('/content/drive')

!pip install pyreadstat

#1 Download All xpt files from website to google drive
from google.colab import drive
import os
import requests
import shutil
from bs4 import BeautifulSoup

# ========================
# STEP 0: MOUNT GOOGLE DRIVE
# ========================
drive.mount('/content/drive')

# Folder in Drive where you want files
DRIVE_FOLDER = "/content/drive/MyDrive/NHANES_Data/nhanes_xpt"

# Delete existing folder if it exists
shutil.rmtree(DRIVE_FOLDER, ignore_errors=True)
print(f"Deleted folder (if it existed): {DRIVE_FOLDER}")

# Create new folder
os.makedirs(DRIVE_FOLDER, exist_ok=True)

# ========================
# STEP 1: CONFIGURATION
# ========================
BASE_URL = "https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx?Component=Laboratory"
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )
}

# ========================
# STEP 2: FETCH HTML PAGE
# ========================
print("Fetching NHANES laboratory data page...")
response = requests.get(BASE_URL, headers=headers)
if response.status_code != 200:
    raise Exception(f"Failed to load page: {response.status_code}")

soup = BeautifulSoup(response.text, "html.parser")

# ========================
# STEP 3: EXTRACT .XPT LINKS
# ========================
links = []
for a in soup.find_all("a", href=True):
    href = a['href']
    if href.lower().endswith(".xpt"):
        links.append("https://wwwn.cdc.gov" + href)

print(f"Found {len(links)} .XPT files.")

# ========================
# STEP 4: DOWNLOAD FILES INTO DRIVE
# ========================
for link in links:
    original_filename = link.split("/")[-1]
    file_path = os.path.join(DRIVE_FOLDER, original_filename)

    if not os.path.exists(file_path):
        r = requests.get(link, headers=headers)
        if r.status_code == 200:
            with open(file_path, "wb") as f:
                f.write(r.content)
            print(f"Downloaded: {original_filename}")
        else:
            print(f"Failed to download {original_filename} ({r.status_code})")
    else:
        print(f"Skipped (already exists): {original_filename}")

print("\nAll files saved to Google Drive folder:")
print(DRIVE_FOLDER)

#1.1 knowing columns of each files
import pandas as pd, os

folder_path = "/content/drive/MyDrive/NHANES_Data/nhanes_xpt"

for file in os.listdir(folder_path):
    if file.lower().endswith(".xpt"):
        path = os.path.join(folder_path, file)
        try:
            df = pd.read_sas(path, format='xport', encoding='utf-8')
            print(f"\n{file} → {len(df.columns)} columns")
            print(df.columns.tolist()[:30])  # show first 30 columns
        except Exception as e:
            print(f"Could not read {file}: {e}")

#1.2 Knowing file containinng core diabetes related columns
import os

folder = "/content/drive/MyDrive/NHANES_Data/nhanes_xpt"
matches = [f for f in os.listdir(folder) if any(k in f.upper() for k in ["GLU","BIO","CHOL","TRIG","GHB","INS","BPX","CREAT"])]
print(matches)

!pip install -U numpy pandas pyreadstat --force-reinstall

#2 Horizonal merging(multiple columns for diffrent year cycle)
import os
import pandas as pd
import pyreadstat

# === CONFIG ===
folder = "/content/drive/MyDrive/NHANES_Data/nhanes_xpt"
output_path = "/content/drive/MyDrive/NHANES_Data/merged_diabetes_dataset.csv"

# === VARIABLES OF INTEREST ===
target_vars = {
    "GLU": ["LBXGLU"],
    "INS": ["LBXIN"],
    "TCHOL": ["LBXTC"],
    "TRIGLY": ["LBXTR"],
    "GHB": ["LBXGH"],
    "BIOPRO": ["LBXSCR", "LBXURIC"],
}

merged_df = None

# === MAIN MERGE LOOP ===
for file in os.listdir(folder):
    fname = file.upper()
    for prefix, cols in target_vars.items():
        if fname.startswith(prefix) and fname.endswith(".XPT"):
            file_path = os.path.join(folder, file)
            try:
                df, meta = pyreadstat.read_xport(file_path)
            except Exception as e:
                print(f"Error reading {file}: {e}")
                continue

            if "SEQN" not in df.columns:
                print(f"Skipping {file}: missing SEQN")
                continue

            # Keep only relevant columns
            keep_cols = ["SEQN"] + [c for c in cols if c in df.columns]
            df = df[keep_cols]

            # Add suffix for cycle (E/F/G etc.)
            cycle = fname.split("_")[-1].split(".")[0]
            df = df.add_suffix(f"_{cycle}")
            df.rename(columns={f"SEQN_{cycle}": "SEQN"}, inplace=True)

            # Merge horizontally on SEQN
            if merged_df is None:
                merged_df = df
            else:
                merged_df = pd.merge(merged_df, df, on="SEQN", how="outer")

            print(f"Merged {file} → shape now {merged_df.shape}")

# === SAVE OUTPUT ===
if merged_df is not None:
    merged_df.to_csv(output_path, index=False)
    print("\nMerge complete!")
    print(f"Rows: {len(merged_df)}, Cols: {len(merged_df.columns)}")
    print(f"Saved merged dataset → {output_path}")
else:
    print("No valid files found.")

#2.1 Vertical Merging(staking rows for multiple cycles)
import os
import pandas as pd
import pyreadstat

input_folder = "/content/drive/MyDrive/NHANES_Data/nhanes_xpt"
output_csv = "/content/drive/MyDrive/NHANES_Data/NHANES_diabetes_merged_vertical.csv"

# Mapping: target name -> possible column names across cycles
var_map = {
    "LBXGLU": ["LBXGLU", "GLU_F", "GLU"],
    "LBXIN": ["LBXIN", "INS"],
    "LBXGH": ["LBXGH", "GHB"],
    "LBXTC": ["LBXTC", "TCHOL"],
    "LBXTR": ["LBXTR", "TRIGLY"],
    "LBXSCR": ["LBXSCR", "CREAT"],
    "URXUAC": ["URXUAC", "URXCR"]
}

all_dfs = []

for file in sorted(os.listdir(input_folder)):
    if not file.lower().endswith(".xpt"):
        continue

    file_path = os.path.join(input_folder, file)
    df, meta = pyreadstat.read_xport(file_path, encoding="latin1")

    # Strip spaces from column names
    df.columns = df.columns.str.strip()

    cols_to_keep = ["SEQN"]
    rename_dict = {}
    for target, options in var_map.items():
        for col in options:
            if col in df.columns:
                cols_to_keep.append(col)
                rename_dict[col] = target
                break

    if len(cols_to_keep) == 1:  # Only SEQN exists
        continue

    df = df[cols_to_keep].copy()
    df.rename(columns=rename_dict, inplace=True)
    df["SEQN"] = pd.to_numeric(df["SEQN"], errors="coerce")
    df.dropna(subset=["SEQN"], inplace=True)
    all_dfs.append(df)

    print(f"Loaded {file}: columns={list(df.columns)} rows={df.shape[0]}")

# Vertical concat
if all_dfs:
    merged = pd.concat(all_dfs, ignore_index=True)
    merged.drop_duplicates(subset=["SEQN"], inplace=True)
    merged.to_csv(output_csv, index=False)
    print(f"\nVertical merge complete → {output_csv}")
    print(f"Shape: {merged.shape}")
else:
    print("No valid data found.")

#2.2 vertical merging with more features
import os
import pandas as pd
import pyreadstat

# === CONFIG ===
input_folder = "/content/drive/MyDrive/NHANES_Data/nhanes_xpt"
output_csv = "/content/drive/MyDrive/NHANES_Data/NHANES_diabetes_merged_features.csv"

# === VARIABLE MAPPING ===
var_map = {
    "LBXGLU": ["LBXGLU", "GLU_F", "GLU"],
    "LBXIN": ["LBXIN", "INS"],
    "LBXGH": ["LBXGH", "GHB"],
    "LBXTC": ["LBXTC", "TCHOL"],
    "LBXTR": ["LBXTR", "TRIGLY"],
    "LBXSCR": ["LBXSCR", "CREAT"],
    "URXUAC": ["URXUAC", "URXCR"],
    "BP_SYS": ["BPXSY1", "BP_SYS"],
    "BP_DIA": ["BPXDI1", "BP_DIA"],
    "LBXHDL": ["LBXHDL"],
    "LBXLDL": ["LBXLDL"],
    "LBXEGFR": ["LBXEGFR"]
}

all_dfs = []

# === HELPER FUNCTIONS ===
def glucose_category(glu):
    if pd.isna(glu): return None
    if glu < 100: return "Normal"
    elif 100 <= glu < 126: return "Prediabetes"
    else: return "Diabetes"

def hba1c_category(hba1c):
    if pd.isna(hba1c): return None
    if hba1c < 5.7: return "Normal"
    elif 5.7 <= hba1c < 6.5: return "Prediabetes"
    else: return "Diabetes"

def bp_category(sys, dia):
    if pd.isna(sys) or pd.isna(dia): return None
    if sys < 120 and dia < 80: return "Normal"
    elif 120 <= sys < 130 and dia < 80: return "Elevated"
    elif 130 <= sys < 140 or 80 <= dia < 90: return "Hypertension Stage 1"
    else: return "Hypertension Stage 2"

def egfr_stage(egfr):
    if pd.isna(egfr): return None
    if egfr >= 90: return 1
    elif 60 <= egfr < 90: return 2
    elif 45 <= egfr < 60: return 3
    elif 30 <= egfr < 45: return 4
    else: return 5

# === READ AND PROCESS FILES ===
for file in sorted(os.listdir(input_folder)):
    if not file.lower().endswith(".xpt"):
        continue

    file_path = os.path.join(input_folder, file)
    try:
        df, meta = pyreadstat.read_xport(file_path, encoding="latin1")
    except Exception as e:
        print(f"Skipping {file}: {e}")
        continue

    df.columns = df.columns.str.strip()  # remove whitespace

    cols_to_keep = ["SEQN"]
    rename_dict = {}
    for target, options in var_map.items():
        for col in options:
            if col in df.columns:
                cols_to_keep.append(col)
                rename_dict[col] = target
                break

    if len(cols_to_keep) == 1:  # Only SEQN exists
        continue

    df = df[cols_to_keep].copy()
    df.rename(columns=rename_dict, inplace=True)
    df["SEQN"] = pd.to_numeric(df["SEQN"], errors="coerce")
    df.dropna(subset=["SEQN"], inplace=True)

    # Add survey cycle from filename (e.g., 'D' from 'GLU_D.xpt')
    cycle = file.split("_")[-1].split(".")[0]
    df["cycle"] = cycle

    all_dfs.append(df)
    print(f"Loaded {file}: columns={list(df.columns)} rows={df.shape[0]}")

# === VERTICAL CONCAT ===
if not all_dfs:
    print("No valid data found.")
else:
    merged = pd.concat(all_dfs, ignore_index=True)
    merged.drop_duplicates(subset=["SEQN"], inplace=True)

    # === DERIVED FEATURES ===
    if "LBXGLU" in merged.columns:
        merged["GLU_category"] = merged["LBXGLU"].apply(glucose_category)
    if "LBXGH" in merged.columns:
        merged["HBA1C_category"] = merged["LBXGH"].apply(hba1c_category)
    if "BP_SYS" in merged.columns and "BP_DIA" in merged.columns:
        merged["BP_category"] = merged.apply(lambda row: bp_category(row["BP_SYS"], row["BP_DIA"]), axis=1)
    if "LBXEGFR" in merged.columns:
        merged["EGFR_stage"] = merged["LBXEGFR"].apply(egfr_stage)

    # Flags for abnormal labs
    if "LBXTR" in merged.columns:
        merged["High_TG"] = merged["LBXTR"] > 150
    if "LBXTC" in merged.columns:
        merged["High_TC"] = merged["LBXTC"] > 200
    if "LBXLDL" in merged.columns:
        merged["High_LDL"] = merged["LBXLDL"] > 130
    if "LBXHDL" in merged.columns:
        merged["Low_HDL"] = merged["LBXHDL"] < 40

    # === SAVE OUTPUT ===
    merged.to_csv(output_csv, index=False)
    print(f"\nVertical merge with features complete → {output_csv}")
    print(f"Shape: {merged.shape}")

#3 Merged data cleaning and preprocessing
import pandas as pd
import numpy as np

# === CONFIG ===
input_csv = "/content/drive/MyDrive/NHANES_Data/NHANES_diabetes_merged_features.csv"
output_csv = "/content/drive/MyDrive/NHANES_Data/NHANES_diabetes_cleaned.csv"

# === STEP 1: LOAD DATA ===
df = pd.read_csv(input_csv)
print(f"Initial shape: {df.shape}")
print(df.head())

# === STEP 2: REPLACE EMPTY STRINGS WITH NaN ===
df.replace("", np.nan, inplace=True)

# === STEP 3: IDENTIFY COLUMN TYPES ===
numeric_cols = df.select_dtypes(include=["float64", "int64"]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

print(f"Numeric columns: {numeric_cols}")
print(f"Categorical columns: {categorical_cols}")

# === STEP 4: FILL MISSING VALUES ===
# Numeric columns: fill NaN with 0
df[numeric_cols] = df[numeric_cols].fillna(0)

# Categorical columns: fill NaN with 'Unknown'
df[categorical_cols] = df[categorical_cols].fillna("Unknown")

# === STEP 5: OPTIONAL - CLEAN FLAGS TO 0/1 ===
# Convert boolean-like columns to 0/1 if needed
flag_cols = ["High_TG", "High_TC", "High_LDL", "Low_HDL"]
for col in flag_cols:
    if col in df.columns:
        df[col] = df[col].replace({True: 1, False: 0, "Unknown": 0, np.nan: 0})

# === STEP 6: SAVE CLEANED DATA ===
df.to_csv(output_csv, index=False)
print(f"Cleaned dataset saved → {output_csv}")
print(f"Final shape: {df.shape}")

#zip file making code for xpt
import shutil
shutil.make_archive("nhanes_xpt", 'zip', "nhanes_xpt")  # create ZIP file

from google.colab import files
files.download("nhanes_xpt.zip")  # to download zip file to local machine

# Xpt to Csv Conversion
from google.colab import drive
import os
import pandas as pd
import shutil

# ========================
# STEP 0: MOUNT GOOGLE DRIVE
# ========================
drive.mount('/content/drive')

# ========================
# STEP 1: DEFINE FOLDERS
# ========================
DRIVE_BASE = "/content/drive/MyDrive/NHANES_Data"
XPT_FOLDER = os.path.join(DRIVE_BASE, "nhanes_xpt")   # Folder with .xpt files
CSV_FOLDER = os.path.join(DRIVE_BASE, "nhanes_csv")   # Folder for .csv output

# ========================
# STEP 2: DELETE OLD CSV FOLDER (IF EXISTS)
# ========================
shutil.rmtree(CSV_FOLDER, ignore_errors=True)
os.makedirs(CSV_FOLDER, exist_ok=True)
print(f"Deleted (if existed) and created new folder: {CSV_FOLDER}")

# ========================
# STEP 3: CONVERT XPT → CSV
# ========================
for xpt_file in os.listdir(XPT_FOLDER):
    if xpt_file.lower().endswith(".xpt"):
        xpt_path = os.path.join(XPT_FOLDER, xpt_file)

        try:
            # Read .XPT file (SAS transport format)
            df = pd.read_sas(xpt_path, format='xport', encoding='latin1')

            # Create corresponding CSV file path
            csv_file = xpt_file.replace(".XPT", ".csv").replace(".xpt", ".csv")
            csv_path = os.path.join(CSV_FOLDER, csv_file)

            # Save as CSV in Drive
            df.to_csv(csv_path, index=False, encoding='latin1')
            print(f"Converted {xpt_file} → {csv_file}")

        except Exception as e:
            print(f"Failed to convert {xpt_file}: {e}")

print("\n🎉 All .XPT files converted to CSV successfully!")
print("Saved in:", CSV_FOLDER)

import shutil
shutil.make_archive("nhanes_csv", 'zip', "nhanes_csv")  # create ZIP file

from google.colab import files
files.download("nhanes_csv.zip")  # to download zip file to local machine

# creating data dictionary for the columns to get meaning and insight out of it
import os
import pandas as pd

CSV_FOLDER = "nhanes_csv"  # Make sure this matches your folder name

#  Get all CSV files properly
files = [f for f in os.listdir(CSV_FOLDER) if f.endswith(".csv")]

data_dict = []

for file in files:
    df = pd.read_csv(os.path.join(CSV_FOLDER, file))
    for col in df.columns:
        data_dict.append({
            "file": file,
            "column_name": col
        })

# Save as CSV
pd.DataFrame(data_dict).to_csv("data_dictionary.csv", index=False)
print("Data dictionary saved as data_dictionary.csv")

# File count and file exist or not under folder script
import os

path = "/content/drive/MyDrive/NHANES_Data/nhanes_csv"
print("Checking folder:", path)

if os.path.exists(path):
    files = [f for f in os.listdir(path) if f.endswith(".csv")]
    print(f"Found {len(files)} CSV files.")
    print("Example files:", files[:5])
else:
    print("Folder not found!")

#method1 combining csv in chunks
from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd

# === CONFIG ===
base_path = "/content/drive/MyDrive/NHANES_Data"
folder_path = os.path.join(base_path, "nhanes_csv") # where CSVs are stored
os.makedirs(folder_path, exist_ok=True)

batch_start = 551      # starting file index (1-based)
batch_end = 754      # ending file index (inclusive)
output_name = f"NHANES_lab_merged_{batch_start}_{batch_end}.csv"

temp_parquet = os.path.join(base_path, f"NHANES_temp_{batch_start}_{batch_end}.parquet")
final_csv = os.path.join(base_path, output_name)

# === LOAD FILES ===
csv_files = sorted([f for f in os.listdir(folder_path) if f.endswith(".csv")])
csv_files = csv_files[batch_start - 1:batch_end]
print(f"Processing batch {batch_start}-{batch_end} → {len(csv_files)} files")

if not csv_files:
    raise ValueError("No files found in this range! Check indexes.")

# === INITIALIZE ===
first_file = csv_files[0]
print(f"Initializing with {first_file} ...")

df = pd.read_csv(os.path.join(folder_path, first_file), engine="python", on_bad_lines="skip")
df.columns = df.columns.str.strip().str.upper()
suffix = os.path.splitext(first_file)[0]
rename_map = {col: f"{col}_{suffix}" for col in df.columns if col != "SEQN"}
df = df.rename(columns=rename_map)
df.to_parquet(temp_parquet, index=False)

# === MERGE LOOP ===
for i, file in enumerate(csv_files[1:], start=2):
    print(f"[{i}/{len(csv_files)}] Merging {file} ...")

    try:
        df_new = pd.read_csv(os.path.join(folder_path, file), engine="python", on_bad_lines="skip")
    except Exception as e:
        print(f"Skipping {file}: {e}")
        continue

    df_new.columns = df_new.columns.str.strip().str.upper()
    if "SEQN" not in df_new.columns:
        print(f"Skipping {file}: SEQN missing")
        continue

    suffix = os.path.splitext(file)[0]
    rename_map = {col: f"{col}_{suffix}" for col in df_new.columns if col != "SEQN"}
    df_new = df_new.rename(columns=rename_map)

    df = pd.read_parquet(temp_parquet)
    df = pd.merge(df, df_new, on="SEQN", how="outer")

    df.to_parquet(temp_parquet, index=False)
    del df, df_new

# === SAVE BATCH MERGE ===
print(f"\nSaving batch result → {final_csv}")
df = pd.read_parquet(temp_parquet)
df.to_csv(final_csv, index=False)
print(f"Done! Saved {final_csv} with shape: {df.shape}")

#method 2 combining csv all files using sqllite
import os
import pandas as pd
import sqlite3

# === CONFIG ===
folder_path = "nhanes_csv"   # folder with your CSVs
db_path = os.path.join(folder_path, "NHANES_lab.db")
final_csv = os.path.join(folder_path, "NHANES_lab_merged_all.csv")

# Collect all CSV files
csv_files = [f for f in os.listdir(folder_path) if f.endswith(".csv")]
csv_files.sort()
print(f"Processing {len(csv_files)} files...")

# Initialize SQLite database
if os.path.exists(db_path):
    os.remove(db_path)
conn = sqlite3.connect(db_path)

# Start with the first file
first_file = csv_files[0]
print(f"Initializing with {first_file} ...")
df = pd.read_csv(os.path.join(folder_path, first_file), engine="python", on_bad_lines="skip")
df.columns = df.columns.str.strip().str.upper()
df.to_sql("merged", conn, index=False, if_exists="replace")

# Merge the rest incrementally
for i, file in enumerate(csv_files[1:], start=2):
    print(f"[{i}/{len(csv_files)}] Merging {file} ...")

    try:
        df_new = pd.read_csv(os.path.join(folder_path, file), engine="python", on_bad_lines="skip")
    except Exception as e:
        print(f"Skipping {file}: {e}")
        continue

    df_new.columns = df_new.columns.str.strip().str.upper()
    if "SEQN" not in df_new.columns:
        continue

    # Add suffix to avoid duplicate column names
    suffix = os.path.splitext(file)[0]
    rename_map = {col: f"{col}_{suffix}" for col in df_new.columns if col != "SEQN"}
    df_new = df_new.rename(columns=rename_map)

    # Save new table
    table_name = f"t{i}"
    df_new.to_sql(table_name, conn, index=False, if_exists="replace")

    # Merge into master table (SQL JOIN)
    merge_query = f"""
        CREATE TABLE merged_new AS
        SELECT COALESCE(m.SEQN, t.SEQN) AS SEQN, *
        FROM merged m
        FULL OUTER JOIN {table_name} t
        ON m.SEQN = t.SEQN
    """
    # SQLite doesn’t support FULL OUTER JOIN natively → workaround:
    merge_query = f"""
        CREATE TABLE merged_new AS
        SELECT m.SEQN,
               m.*,
               t.*
        FROM merged m
        LEFT JOIN {table_name} t ON m.SEQN = t.SEQN
        UNION
        SELECT t.SEQN,
               m.*,
               t.*
        FROM {table_name} t
        LEFT JOIN merged m ON m.SEQN = t.SEQN
    """

    conn.execute("DROP TABLE IF EXISTS merged_new;")
    conn.execute(merge_query)
    conn.execute("DROP TABLE merged;")
    conn.execute("ALTER TABLE merged_new RENAME TO merged;")
    conn.commit()

# Export final merged dataset
print(f"Exporting to {final_csv} ...")
final_df = pd.read_sql("SELECT * FROM merged", conn)
final_df.to_csv(final_csv, index=False)
conn.close()
print("Done! Final file:", final_csv)

# merging only core(imp) diabetes realted files by filtler
from google.colab import drive
import os
import pandas as pd

# =========================
# STEP 0: Mount Google Drive
# =========================
drive.mount('/content/drive')

# =========================
# CONFIGURATION
# =========================
BASE_DIR = "/content/drive/MyDrive/NHANES_Data"
folder_path = os.path.join(BASE_DIR, "nhanes_csv")          # input folder with all CSVs
merged_folder = os.path.join(BASE_DIR, "nhanes_merged_csv") # output folder

os.makedirs(merged_folder, exist_ok=True)

temp_parquet = os.path.join(merged_folder, "NHANES_lab_temp.parquet")
final_csv = os.path.join(merged_folder, "NHANES_lab_diabetes_imp.csv")

# =========================
# STEP 1: Select Diabetes-Related Files
# =========================
keywords = [
    "GLU", "GLUC", "INS", "OGTT", "GHB", "A1C", "DIQ", "FAST",
    "BIO", "CHEM", "CHOL", "HDL", "LDL", "TRIG", "LIP", "CRP", "ALB", "CRE",
    "HORM", "TEST", "ESTR", "PROG", "CORT", "TSH", "T4", "THY", "IGF",
    "RENAL", "URIC", "URIN", "MICRO", "AST", "ALT", "GGT",
    "VIT", "IRON", "FERR", "B12", "FOL", "ZINC", "MAG", "CAL",
    "HSCRP", "CRP", "CYTOK", "IL", "TNF", "IMM",
    "BIOPRO", "LAB", "LBX", "LBD"
]

csv_files = [f for f in os.listdir(folder_path) if f.endswith(".csv")]
csv_files = [f for f in csv_files if any(k in f.upper() for k in keywords)]
csv_files.sort()

print(f"Found {len(csv_files)} diabetes-related files to merge")

# =========================
# STEP 2: Merge Step-by-Step
# =========================
if not csv_files:
    raise Exception("No matching CSV files found in folder.")

first_file = csv_files[0]
print(f"Initializing with {first_file} ...")

df = pd.read_csv(os.path.join(folder_path, first_file), engine="python", on_bad_lines="skip")
df.columns = df.columns.str.strip().str.upper()
suffix = os.path.splitext(first_file)[0]
rename_map = {col: f"{col}_{suffix}" for col in df.columns if col != "SEQN"}
df = df.rename(columns=rename_map)
df.to_parquet(temp_parquet, index=False)

for i, file in enumerate(csv_files[1:], start=2):
    print(f"[{i}/{len(csv_files)}] Merging {file} ...")

    try:
        df_new = pd.read_csv(os.path.join(folder_path, file), engine="python", on_bad_lines="skip")
    except Exception as e:
        print(f"Skipping {file}: {e}")
        continue

    df_new.columns = df_new.columns.str.strip().str.upper()
    if "SEQN" not in df_new.columns:
        continue

    suffix = os.path.splitext(file)[0]
    rename_map = {col: f"{col}_{suffix}" for col in df_new.columns if col != "SEQN"}
    df_new = df_new.rename(columns=rename_map)

    df = pd.read_parquet(temp_parquet)
    df = pd.merge(df, df_new, on="SEQN", how="outer")
    df.to_parquet(temp_parquet, index=False)
    del df, df_new

# =========================
# STEP 3: Save Final File
# =========================
print(f"Saving final CSV → {final_csv}")
df = pd.read_parquet(temp_parquet)
df.to_csv(final_csv, index=False)
print("Done! Final file saved to:", final_csv)

# Data Cleaning and preprocessing

from google.colab import drive
import pandas as pd
import numpy as np
import os

# =========================
# STEP 0: Mount Drive
# =========================
drive.mount('/content/drive')

# =========================
# STEP 1: Define Paths
# =========================
BASE_DIR = "/content/drive/MyDrive/NHANES_Data"
INPUT_FILE = os.path.join(BASE_DIR, "nhanes_merged_csv", "NHANES_lab_diabetes_imp.csv")
OUTPUT_FILE = os.path.join(BASE_DIR, "nhanes_cleaned.csv")

# =========================
# STEP 2: Load Dataset
# =========================
print("Loading dataset...")
df = pd.read_csv(INPUT_FILE, low_memory=False)
print(f"Loaded with shape: {df.shape}")

# =========================
# STEP 3: Basic Cleanup
# =========================
df = df.drop_duplicates()
print("Removed duplicate rows:", df.shape)

df = df.dropna(axis=1, how="all")
print("Dropped empty columns:", df.shape)

if "SEQN" in df.columns:
    df = df.dropna(subset=["SEQN"])
    df["SEQN"] = df["SEQN"].astype(int)
else:
    print("SEQN column not found!")

# =========================
# STEP 4: Handle Missing Values
# =========================
missing_pct = df.isnull().mean() * 100
drop_cols = missing_pct[missing_pct > 90].index
df = df.drop(columns=drop_cols)
print(f"Dropped {len(drop_cols)} columns with >90% missing values")

num_cols = df.select_dtypes(include=[np.number]).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

cat_cols = df.select_dtypes(exclude=[np.number]).columns
for col in cat_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values handled.")

# =========================
# STEP 5: Fix Column Names & Outliers
# =========================
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(r'[^A-Za-z0-9_]+', '_', regex=True)

for col in num_cols:
    if df[col].nunique() > 10:
        upper = df[col].mean() + 3 * df[col].std()
        lower = df[col].mean() - 3 * df[col].std()
        df = df[(df[col] >= lower) & (df[col] <= upper)]

print("Outliers handled.")

# =========================
# STEP 6: Save Cleaned Dataset
# =========================
df.to_csv(OUTPUT_FILE, index=False)
print(f"Cleaned dataset saved as {OUTPUT_FILE}")
print(f"Final shape: {df.shape}")

file_path = "nhanes_csv/CBC_E.csv"
df = pd.read_csv(file_path)

df.head()

len(df['LBXLYPCT'])

rows_with_nan = df[df.isna().any(axis=1)]

len(rows_with_nan)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score
from imblearn.over_sampling import SMOTE

# === Load dataset ===
df = pd.read_csv("/content/drive/MyDrive/NHANES_Data/NHANES_diabetes_cleaned.csv")

# === Drop ID column and set target ===
target = "GLU_category"
X = df.drop(columns=["SEQN", target])
y = df[target]

# === Encode categorical columns ===
for col in X.columns:
    if X[col].dtype == "object":
        le = LabelEncoder()
        X[col] = le.fit_transform(X[col].astype(str))

# === Encode target as well (if string) ===
if y.dtype == "object":
    le_y = LabelEncoder()
    y = le_y.fit_transform(y)

# === Split data ===
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# === Balance data with SMOTE ===
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

# === Scale ===
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_res)
X_test_scaled = scaler.transform(X_test)

# === Train model ===
model = LogisticRegression(max_iter=1000, penalty='l2', C=0.5)
model.fit(X_train_scaled, y_train_res)

# === Evaluate ===
y_pred = model.predict(X_test_scaled)
y_pred_proba = model.predict_proba(X_test_scaled)

print("Model training complete.\n")
print(classification_report(y_test, y_pred))
print("ROC-AUC (ovr, probabilities):", roc_auc_score(y_test, y_pred_proba, multi_class='ovr'))

